### ISSUE TITLE
Extension does not work on Youtube and WhatsApp Web

### ISSUE THREAD

**Issue by gspereira** [wokalek/tab-volume#36]
All my volume control extensions kinda just broke in the last month, this one is the first that actually worked after that.
But for some reason I can't change the volume on youtube or whatsapp web, already tried to tinker with some browser configurations, but still no luck.
Im using Microsoft Edge, and its all up to date.

**Comment by wokalek** [comment]
@gspereira 

Hello! It's strange that it doesn't work on YouTube. I use the extension myself, including on YouTube, all the time - everything works.

In fact, I don’t understand how you use my extension in the Microsoft Edge browser, because it was written specifically for Google Chrome and is [used there](https://chromewebstore.google.com/detail/tab-volume/nfconmpaofmnebmmnoinlbgfocaimkah).

How did you install it in Microsoft Edge? (:
Edge's store [doesn't have my extension](https://microsoftedge.microsoft.com/addons/search/tab%20volume).

**Comment by wokalek** [comment]
However, I tried to load the unpacked prod version of the extension into Microsoft Edge - and it worked (I never tested it because I made it specifically for Chrome), lol.

It seems to me that everything should work on the latest version of Edge, since Edge is made on the basis of Chromium.

![image](https://github.com/wokalek/tab-volume/assets/23037847/68fea4b0-32c2-4bbe-b838-f18280f04e91)

**Comment by wokalek** [comment]
Perhaps you are using a version of Edge that is < 116. The features that are used in my extension assume that the user has a Chromium version of at least 116 (Google Chrome exactly matches the Chromium version, for example). Whether Edge lives up to it, I don't know.

https://github.com/wokalek/tab-volume/blob/3da36a34b0d279685385312ee968d68db85b0c86/src/manifest.ts#L11

**Comment by gspereira** [comment]
Thats strange, it is updated to the last version, but for some reason it still won't work for those cases. I there a way to debug it and see what can be causing it?

![image](https://github.com/wokalek/tab-volume/assets/25405333/9a86a2a9-a253-4ebc-82a3-696d6929a0c1)

**Comment by gspereira** [comment]
> @gspereira
> 
> Hello! It's strange that it doesn't work on YouTube. I use the extension myself, including on YouTube, all the time - everything works.
> 
> In fact, I don’t understand how you use my extension in the Microsoft Edge browser, because it was written specifically for Google Chrome and is [used there](https://chromewebstore.google.com/detail/tab-volume/nfconmpaofmnebmmnoinlbgfocaimkah).
> 
> How did you install it in Microsoft Edge? (: Edge's store [doesn't have my extension](https://microsoftedge.microsoft.com/addons/search/tab%20volume).

You can install chrome extensions on edge hahaha

**Comment by wokalek** [comment]
> You can install chrome extensions on edge hahaha


I really didn't know that hahaha :)

I tested it on version 122 (the latest for me on my computer) - everything works. In youtube and watsapp web... 

![image](https://github.com/wokalek/tab-volume/assets/23037847/36e9f2a8-3e2e-42be-bae6-3985f9950e40)

![image](https://github.com/wokalek/tab-volume/assets/23037847/d09d9afc-4fdc-46c6-97ba-adea2751b8bb)

So on YouTube the problem only occurs sometimes? 

When you encounter a problem, please check if any errors are displayed in the console of the extension window. You can do it like this:

![image](https://github.com/wokalek/tab-volume/assets/23037847/4e4cb770-2172-440f-a6fe-26ca1aad1c0e)

**Comment by gspereira** [comment]
Thank you, In the end I had to downgrade the browser to make it work, maybe it will still work in the future, thank you very much for your help.
